export default defineEventHandler(async () => {
  return [
    {
      id: 1,
      name: "ролл ясай",
      weight: 185,
      description:
        "Огурец, авокадо, помидор, болгарский перец, листья салата, кунжут",
      price: 200,
      heart: false,
      count: 0,
    },
    {
      id: 2,
      name: "Мясные роллы",
      weight: 260,
      description:
        "Огурец, авокадо, помидор, болгарский перец, листья салата, кунжут",
      price: 240,
      heart: true,
      count: 0,
    },
    {
      id: 3,
      name: "ролл лайт",
      weight: 190,
      description: "Листья салата, огурец, перец, помидор, сырный соус, чипсы",
      price: 165,
      heart: true,
      count: 0,
    },
    {
      id: 4,
      name: "ролл веган",
      weight: 230,
      description: "Листья салата, авокадо, огурец, спаржа, сивид чука, кунжут",
      price: 200,
      heart: true,
      count: 0,
    },
    {
      id: 5,
      name: "ролл чиро",
      weight: 210,
      description:
        "Листья салата, копченая курица, болгарский перец, твердый сыр, чесночный соус",
      price: 210,
      heart: true,
      count: 0,
    },
    {
      id: 6,
      name: "ролл тайол",
      weight: 215,
      description: "Огурец, помидор, сыр творожный, бекон, сыр маасдам",
      price: 215,
      heart: true,
      count: 0,
    },
    {
      id: 7,
      name: "ролл Батакон",
      weight: 220,
      description: "Огурец, сыр творожный, бекон",
      price: 230,
      heart: true,
      count: 0,
    },
    {
      id: 8,
      name: "ролл калипсо",
      weight: 195,
      description: "Сыр творожный, огурец, мидии, стружка тунца",
      price: 185,
      heart: true,
      count: 0,
    },
    {
      id: 9,
      name: "ролл кавьяр",
      weight: 240,
      description: "Сыр творожный, помидор, огурец, мидии, майонез",
      price: 200,
      heart: true,
      count: 0,
    },
    {
      id: 10,
      name: "ролл чипу",
      weight: 190,
      description: "Сыр творожный, лосось, томаго, стружка тунца",
      price: 180,
      heart: true,
      count: 0,
    },
    {
      id: 11,
      name: "ролл катана",
      weight: 240,
      description: "Сыр творожный, лосось, томаго, стружка тунца",
      price: 250,
      heart: true,
      count: 0,
    },
    {
      id: 12,
      name: "ролл мишику",
      weight: 210,
      description:
        "Угорь, краб, огурец, масаго, сыр творожный,  сырный соус, картофельные чипсы",
      price: 260,
      heart: true,
      count: 0,
    },
    {
      id: 13,
      name: "ролл ясай",
      weight: 185,
      description:
        "Огурец, авокадо, помидор, болгарский перец, листья салата, кунжут",
      price: 200,
      heart: false,
      count: 0,
    },
    {
      id: 14,
      name: "ролл веган",
      weight: 230,
      description: "Листья салата, авокадо, огурец, спаржа, сивид чука, кунжут",
      price: 200,
      heart: true,
      count: 0,
    },
    {
      id: 15,
      name: "ролл лайт",
      weight: 190,
      description: "Листья салата, огурец, перец, помидор, сырный соус, чипсы",
      price: 165,
      heart: true,
      count: 0,
    },
    {
      id: 16,
      name: "ролл веган",
      weight: 230,
      description: "Листья салата, авокадо, огурец, спаржа, сивид чука, кунжут",
      price: 200,
      heart: true,
      count: 0,
    },
  ];
});
